version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DataTransformationExample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5tgrg39tlnht"
s3_prefix = "DataTransformationExample"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
